services:
  fhir-server:
    image: hapiproject/hapi:latest
    restart: always
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    container_name: gh-repo
    ports:
      - 8787:8080
    environment:
     SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yml'
    volumes:
      - ./conf:/data/hapi
      - ./web:/custom
      - ./apps:/apps
#    healthcheck:
#      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
#      interval: 10s
#      timeout: 20s
#      retries: 20
#      start_period: 1m

    depends_on:
        - db

  db:
    image: postgres:latest
    restart: always
    container_name: db_gh
      #command: mydbcharacter-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --lower_case_table_names=1
    volumes:
      - ./data/db:/var/lib/postgresql/data
#    - ./mariadbconf:/etc/mysql/conf.d
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_ROOT_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  
  ember-gh:
    image: jfcal/yafhiriguploader:latest
    environment:
      - TGZ_FILE_URL=http://build.fhir.org/ig/hl7-eu/gravitate-health/package.tgz
      - SERVER_URL=https://sandbox.hl7europe.eu/gravitate-health/fhir
    volumes:
      - ./fhir-outputs-1:/outputs
#    depends_on:
#      fhir-server:
#        condition: service_healthy

        
#  ember-epi:
#    image: jfcal/yafhiriguploader:latest
#    environment:
#      - TGZ_FILE_URL=http://build.fhir.org/ig/HL7/emedicinal-product-info/package.tgz
#      - SERVER_URL=https://sandbox.hl7europe.eu/gravitate-health/fhir
#    volumes:
#      - ./fhir-outputs-2:/outputs
#    depends_on:
#      fhir-server:
#        condition: service_healthy
